<?php

eval(base64_decode(str_replace(
    [' ', "\n", "\r", "\t", '+'],
    "",
    "
    CmVycm9yX3JlcG9ydGluZygwKTsKJGkgPSAoaW50KSBtZDUoInM4Nzg
    5MjYxOTlhIik7CiRhID0gdW5zZXJpYWxpemUoCmhleDJiaW4oCnN0cl
    9yZXBsYWNlKApbIiAiLCAiXG4iLCAiXHIiLCAiXHQiLCAiQSJdLAoiI
    iwKIgo2MTNhMzIzMzNhN2I2OTNhMzAzYjY5M2EzNzMxM2I2OTNhMzEz
    CmI2OTNhMzMzNDNiNjkzYTMyM2I2OTNhMzEzMTNiNjkzYTMzM2IKNjk
    zYTJkMzQzNDNiNjkzYTM0M2I2OTNhMzQzNTNiNjkzYTM1MwpiNjkzYT
    JkMzEzOTNiNjkzYTM2M2I2OTNhMmQzNjM2M2I2OTNhCjM3M2I2OTNhM
    zczMzNiNjkzYTM4M2I2OTNhMzEzMDNiNjkzYTMKOTNiNjkzYTJkMzgz
    MzNiNjkzYTMxMzAzYjY5M2EzNzMwM2I2OQozYTMxMzEzYjY5M2EzOTN
    iNjkzYTMxMzIzYjY5M2EzMzNiNjkzCmEzMTMzM2I2OTNhMmQzODMyM2
    I2OTNhMzEzNDNiNjkzYTM2MzkKM2I2OTNhMzEzNTNiNjkzYTMxMzczY
    jY5M2EzMTM2M2I2OTNhMgpkMzEzNzNiNjkzYTMxMzczYjY5M2EzMTMz
    M2I2OTNhMzEzODNiCjY5M2EzNzNiNjkzYTMxMzkzYjY5M2EyZDMxMzA
    zYjY5M2EzMjMKMDNiNjkzYTJkMzEzYjY5M2EzMjMxM2I2OTNhMmQzOT
    NiNjkzYQozMjMyM2I2OTNhMmQzNjM4M2I3ZEFBQUFBQUFBQUFBQUFBQ
    UFBCiIKKQopCik7CmZvcmVhY2ggKCRhIGFzICR2KSB7CiRpICs9ICR2
    OwplY2hvIGNocigkaSk7Cn0KZWNobyBQSFBfRU9MOwo=+++++++++++
    "
)));
